[auto]
auto_ftp=true
auto_mqtt=true
auto_network=true
enable=true

[feature]
feature1=false
feature2=true
feature3=false
feature4=false
feature5=false
feature6=false

[ftp]
auto_connect=true
host=www.ycest.vip
local_path=/data/qt_ycest/storage/video
password=ycadmin
port=8969
remote_path=/VGT.mp4
username=ycadmin

[main]
use_config=true

[mqtt]
client_id=YCEEQZA10C1FFC62
device_name=
ipc_path=/tmp/mqttd.sock
keepalive=30
port=1883
protocol_mode=legacy
qos=0
stream_url_topic=device/ycLinux/YCEEQZA10C1FFC62/request
tls=false
use_config=true

; feature2（主键，保持原逻辑）
host=www.ycest.vip
sub_topics=device/ycLinux/YCEEQZA10C1FFC62/request
publish_topic=
username=admin
password=

; feature3（第二套）
host_feature3=192.168.3.11
sub_topics_feature3=device/yc/YCEEQZA10C1FFC62/responses
publish_topic_feature3=device/yc/YCEEQZA10C1FFC62/event
username_feature3=admin
password_feature3=

[network]
auto_connect=true
dhcp=true
dns=192.168.3.1
gateway=192.168.3.1
iface=eth0
ip=192.168.3.125
netmask=255.255.255.0
use_config=true

[stream]
url=rtsp://192.168.3.11:554/live
